"""add notes to expenses

Revision ID: 200f76059b3b
Revises: a1b2c3d4e5f6
Create Date: 2026-08-03 09:07:05.944551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200f76059b3b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
