"""Add investment tracking to UserApiSettings

Revision ID: 3fd04a714f6a
Revises: 4a74d3b48385
Create Date: 2025-12-28 02:24:13.537889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd04a714f6a'
down_revision = '4a74d3b48385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_tracking_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_settings', schema=None) as batch_op:
        batch_op.drop_column('investment_tracking_enabled')

    # ### end Alembic commands ###
