"""Add SimpleFin settings to UserApiSettings

Revision ID: 4a74d3b48385
Revises: 0abe58d0fc8d
Create Date: 2025-12-28 02:10:36.256539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a74d3b48385'
down_revision = '0abe58d0fc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('data_source')
        batch_op.drop_column('exchange')

    with op.batch_alter_table('user_api_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simplefin_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('simplefin_access_url', sa.Text(), nullable=True))
        batch_op.drop_column('preferred_data_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_data_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('simplefin_access_url')
        batch_op.drop_column('simplefin_enabled')

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
