"""Add preferred_data_source to UserApiSettings model

Revision ID: 5c900eb00454
Revises: 
Create Date: 2025-05-01 16:30:50.740718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c900eb00454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('exchange', sa.String(length=10), nullable=True))
    op.add_column('investments', sa.Column('data_source', sa.String(length=20), nullable=True))
    op.add_column('user_api_settings', sa.Column('preferred_data_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_api_settings', 'preferred_data_source')
    op.drop_column('investments', 'data_source')
    op.drop_column('investments', 'exchange')
    # ### end Alembic commands ###
